# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('address', models.CharField(max_length=80, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人/电话')),
                ('scope', models.CharField(blank=True, max_length=100, null=True, verbose_name='经营范围')),
            ],
            options={
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
    ]
