# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=20, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('standard', models.CharField(max_length=50, verbose_name='规格')),
                ('type', models.CharField(max_length=50, verbose_name='型号')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('safe_num', models.IntegerField(default=0, verbose_name='安全数')),
                ('image', models.ImageField(upload_to='img')),
            ],
            options={
                'verbose_name_plural': '配件表',
                'ordering': ['p_id'],
            },
        ),
    ]
