# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0002_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='p_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='编号'),
        ),
    ]
