# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0003_auto_20171129_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='standard',
            field=models.CharField(max_length=50, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='型号'),
        ),
    ]
