# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0005_auto_20171129_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='价格')),
                ('in_num', models.IntegerField(verbose_name='数量')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Parts', verbose_name='配件编号')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name_plural': '入库表',
                'ordering': ['-date'],
            },
        ),
    ]
