# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0006_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='设备')),
            ],
        ),
    ]
