# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0007_equi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_num', models.IntegerField(verbose_name='数量')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Parts', verbose_name='配件编号')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='员工')),
            ],
            options={
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Weixiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pline', models.CharField(choices=[('4', 'PG2'), ('5', 'PD3'), ('6', 'PG3'), ('7', '其他')], max_length=1, verbose_name='线别')),
                ('date_s', models.DateField(verbose_name='发生日期')),
                ('description', models.CharField(max_length=200, verbose_name='故障/异常/保养维护描述')),
                ('reason', models.CharField(choices=[('295', '未纳入保养'), ('296', '保养不足'), ('297', '正常损耗'), ('298', '操作不当'), ('299', '5S改善'), ('300', '遗留问题'), ('301', '设计缺陷'), ('302', '维护保养')], max_length=4, verbose_name='发生原因')),
                ('method', models.CharField(max_length=200, verbose_name='排除方法')),
                ('date_e', models.DateField(verbose_name='解决时间')),
                ('date_n', models.DateField(verbose_name='下次计划维修时间')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='话费')),
                ('finish', models.BooleanField(verbose_name='是否完成')),
            ],
        ),
        migrations.AlterModelOptions(
            name='equi',
            options={'verbose_name_plural': '设备'},
        ),
        migrations.AddField(
            model_name='weixiu',
            name='equi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Equi', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='weixiu',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Staff', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='output',
            name='weixiu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peijian.Weixiu', verbose_name='维修单'),
        ),
    ]
