# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0008_auto_20171129_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='output',
            options={'verbose_name_plural': '出库单'},
        ),
        migrations.AlterModelOptions(
            name='weixiu',
            options={'verbose_name_plural': '维修单'},
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='date_e',
            field=models.DateField(null=True, verbose_name='解决时间'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='date_n',
            field=models.DateField(null=True, verbose_name='下次计划维修时间'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='method',
            field=models.CharField(max_length=200, null=True, verbose_name='排除方法'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='reason',
            field=models.CharField(choices=[('295', '未纳入保养'), ('296', '保养不足'), ('297', '正常损耗'), ('298', '操作不当'), ('299', '5S改善'), ('300', '遗留问题'), ('301', '设计缺陷'), ('302', '维护保养')], max_length=4, null=True, verbose_name='发生原因'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peijian.Staff', verbose_name='员工'),
        ),
    ]
