# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peijian', '0009_auto_20171129_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixiu',
            name='description',
            field=models.TextField(max_length=200, verbose_name='故障/异常/保养维护描述'),
        ),
        migrations.AlterField(
            model_name='weixiu',
            name='method',
            field=models.TextField(max_length=200, null=True, verbose_name='排除方法'),
        ),
    ]
