# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pline',
            name='zw',
            field=models.CharField(max_length=50, null=True, verbose_name='中文'),
        ),
    ]
