# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0002_pline_zw'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuZhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='故障原因')),
                ('shu', models.IntegerField(default=0, verbose_name='故障数量')),
                ('f_date', models.DateTimeField(verbose_name='发生时间')),
                ('x_date', models.DateTimeField(verbose_name='修复时间')),
                ('banci', models.CharField(choices=[('A', 'A班'), ('B', 'B班')], default='A', max_length=1)),
            ],
            options={
                'verbose_name_plural': '故障表',
            },
        ),
        migrations.CreateModel(
            name='JiBen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pline', models.CharField(choices=[('1', 'PG2'), ('2', 'PG3'), ('3', 'PD3')], default='1', max_length=1, verbose_name='线别')),
                ('date', models.DateField(verbose_name='日期')),
                ('kjcs', models.IntegerField(default=0, verbose_name='开机次数')),
                ('clmj', models.IntegerField(default=0, verbose_name='处理面积')),
                ('trl', models.IntegerField(default=0, verbose_name='投入量')),
                ('scss', models.IntegerField(default=0, verbose_name='生产时数')),
                ('yygs', models.IntegerField(default=0, verbose_name='应有杆数')),
                ('bl', models.IntegerField(default=0, verbose_name='不良数')),
                ('amp', models.IntegerField(default=0, verbose_name='安培小时')),
                ('shui', models.IntegerField(default=0, verbose_name='用水量')),
                ('dian', models.IntegerField(default=0, verbose_name='用电量')),
                ('ddw', models.IntegerField(default=0, verbose_name='品质等待')),
                ('cfw', models.IntegerField(default=0, verbose_name='换班吃饭')),
                ('dqw', models.IntegerField(default=0, verbose_name='货源短缺')),
                ('wcw', models.IntegerField(default=0, verbose_name='开关机误差')),
                ('qtw', models.IntegerField(default=0, verbose_name='其他')),
                ('sc_count', models.IntegerField(default=0, verbose_name='色差数量')),
                ('scy', models.CharField(choices=[('c', '操作不当'), ('y', '药液失调'), ('g', '故障设备')], default='操作不当', max_length=1, verbose_name='色差原因')),
                ('mh_count', models.IntegerField(default=0, verbose_name='膜厚数量')),
                ('mhy', models.CharField(choices=[('c', '操作不当'), ('j', '计算错误'), ('g', '故障设备')], default='操作不当', max_length=1, verbose_name='膜厚原因')),
                ('cs_count', models.IntegerField(default=0, verbose_name='错色数量')),
                ('csy', models.CharField(choices=[('c', '操作不当'), ('p', '票据错误'), ('g', '故障设备')], default='操作不当', max_length=1, verbose_name='错色原因')),
                ('qp_count', models.IntegerField(default=0, verbose_name='气泡数量')),
                ('qpy', models.CharField(choices=[('m', '膜厚偏高'), ('s', '酸洗不良'), ('g', '故障设备')], default='膜厚偏高', max_length=1, verbose_name='气泡原因')),
                ('ct_count', models.IntegerField(default=0, verbose_name='出铁数量')),
                ('cty', models.CharField(choices=[('d', '导电不良'), ('f', '挂具不符'), ('t', '脱脂不良'), ('g', '故障设备')], default='导电不良', max_length=1, verbose_name='出铁原因')),
                ('qt_count', models.IntegerField(default=0, verbose_name='其他数量')),
                ('qty', models.CharField(choices=[('j', '基材不良'), ('h', '素材黑点'), ('s', '素材生锈')], default='基材不良', max_length=1, verbose_name='其他原因')),
            ],
            options={
                'verbose_name_plural': '基本信息表',
                'ordering': ['-date', 'pline'],
            },
        ),
        migrations.CreateModel(
            name='Yao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yao', models.CharField(choices=[('1', '160'), ('2', '162'), ('3', '173'), ('4', '175'), ('5', '184G')], max_length=1, verbose_name='药水')),
                ('clmj', models.IntegerField(default=0, verbose_name='处理面积')),
                ('clsl', models.IntegerField(default=0, verbose_name='处理数量')),
                ('clts', models.IntegerField(default=0, verbose_name='处理桶（杆）数')),
                ('ljmj', models.IntegerField(default=0, verbose_name='累积面积')),
                ('jiben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pline.JiBen')),
            ],
        ),
        migrations.DeleteModel(
            name='pline',
        ),
        migrations.AddField(
            model_name='guzhang',
            name='jiben',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pline.JiBen'),
        ),
    ]
