# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0003_auto_20171115_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guzhang',
            name='banci',
            field=models.CharField(choices=[('A', 'A班'), ('B', 'B班')], max_length=1),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='csy',
            field=models.CharField(choices=[('c', '操作不当'), ('p', '票据错误'), ('g', '故障设备')], max_length=1, verbose_name='错色原因'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='cty',
            field=models.CharField(choices=[('d', '导电不良'), ('f', '挂具不符'), ('t', '脱脂不良'), ('g', '故障设备')], max_length=1, verbose_name='出铁原因'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='mhy',
            field=models.CharField(choices=[('c', '操作不当'), ('j', '计算错误'), ('g', '故障设备')], max_length=1, verbose_name='膜厚原因'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='pline',
            field=models.CharField(choices=[('1', 'PG2'), ('2', 'PG3'), ('3', 'PD3')], max_length=1, verbose_name='线别'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='qpy',
            field=models.CharField(choices=[('m', '膜厚偏高'), ('s', '酸洗不良'), ('g', '故障设备')], max_length=1, verbose_name='气泡原因'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='qty',
            field=models.CharField(choices=[('j', '基材不良'), ('h', '素材黑点'), ('s', '素材生锈')], max_length=1, verbose_name='其他原因'),
        ),
        migrations.AlterField(
            model_name='jiben',
            name='scy',
            field=models.CharField(choices=[('c', '操作不当'), ('y', '药液失调'), ('g', '故障设备')], max_length=1, verbose_name='色差原因'),
        ),
        migrations.AlterField(
            model_name='yao',
            name='yao',
            field=models.CharField(choices=[('1', '441A'), ('2', '444CS'), ('3', '447MD'), ('4', '124'), ('5', '444s'), ('5', '447s')], max_length=1, verbose_name='药水'),
        ),
    ]
