# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0005_auto_20171117_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiaPD3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('ct', models.IntegerField(default=0, verbose_name='初脱')),
                ('cd', models.IntegerField(default=0, verbose_name='初电')),
                ('cdpj', models.IntegerField(default=0, verbose_name='初电片碱')),
                ('dj', models.IntegerField(default=0, verbose_name='电解')),
                ('djpj', models.IntegerField(default=0, verbose_name='电解片碱')),
                ('ys', models.IntegerField(default=0, verbose_name='盐酸')),
                ('xb', models.IntegerField(default=0, verbose_name='锌板')),
                ('lj', models.IntegerField(default=0, verbose_name='粒碱')),
                ('nz98', models.IntegerField(default=0, verbose_name='NZ-98')),
                ('nzfb', models.IntegerField(default=0, verbose_name='NZ-FB')),
                ('h0616y', models.IntegerField(default=0, verbose_name='H-0616Y')),
                ('hztzj', models.IntegerField(default=0, verbose_name='HZ调整剂')),
                ('j124', models.IntegerField(default=0, verbose_name='124加药量')),
                ('j44s', models.IntegerField(default=0, verbose_name='44S加药量')),
                ('j44h', models.IntegerField(default=0, verbose_name='44H加药量')),
                ('j447s1', models.IntegerField(default=0, verbose_name='447S1加药量')),
                ('j447s2', models.IntegerField(default=0, verbose_name='447S2加药量')),
                ('j447s3', models.IntegerField(default=0, verbose_name='447S3加药量')),
                ('j447r3', models.IntegerField(default=0, verbose_name='447R3加药量')),
                ('j118n', models.IntegerField(default=0, verbose_name='118N加药量')),
            ],
        ),
    ]
