# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0007_auto_20171117_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiaPG3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('sc30', models.IntegerField(default=0, verbose_name='SC-30')),
                ('hcl', models.IntegerField(default=0, verbose_name='HCL')),
                ('rc30', models.IntegerField(default=0, verbose_name='RC-30')),
                ('rc25st', models.IntegerField(default=0, verbose_name='RC-25ST')),
                ('sm', models.IntegerField(default=0, verbose_name='DS-31')),
                ('naoh', models.IntegerField(default=0, verbose_name='NAOH')),
                ('xb', models.IntegerField(default=0, verbose_name='锌板')),
                ('lj', models.IntegerField(default=0, verbose_name='粒碱')),
                ('nz200r', models.IntegerField(default=0, verbose_name='NZ-200R')),
                ('nzrba', models.IntegerField(default=0, verbose_name='NZ-RBA')),
                ('h0616y', models.IntegerField(default=0, verbose_name='H-0616Y')),
                ('hztzj', models.IntegerField(default=0, verbose_name='HZ调整剂')),
                ('j441a', models.IntegerField(default=0, verbose_name='441A')),
                ('j444cs', models.IntegerField(default=0, verbose_name='444CS')),
                ('j444cst', models.IntegerField(default=0, verbose_name='444CST')),
            ],
            options={
                'verbose_name_plural': 'PG3加药表',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j118n',
            field=models.IntegerField(default=0, verbose_name='118N'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j124',
            field=models.IntegerField(default=0, verbose_name='124'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j447r3',
            field=models.IntegerField(default=0, verbose_name='447R3'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j447s1',
            field=models.IntegerField(default=0, verbose_name='447S1'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j447s2',
            field=models.IntegerField(default=0, verbose_name='447S2'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j447s3',
            field=models.IntegerField(default=0, verbose_name='447S3'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j44h',
            field=models.IntegerField(default=0, verbose_name='44H'),
        ),
        migrations.AlterField(
            model_name='jiapd3',
            name='j44s',
            field=models.IntegerField(default=0, verbose_name='44S'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j118',
            field=models.IntegerField(default=0, verbose_name='ZTB-118'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j441a',
            field=models.IntegerField(default=0, verbose_name='441A'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j444cs',
            field=models.IntegerField(default=0, verbose_name='444CS'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j444cst',
            field=models.IntegerField(default=0, verbose_name='444CST'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j447md1',
            field=models.IntegerField(default=0, verbose_name='447MD1'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j447md2',
            field=models.IntegerField(default=0, verbose_name='447MD2'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j447md3',
            field=models.IntegerField(default=0, verbose_name='447MD3'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j447md4',
            field=models.IntegerField(default=0, verbose_name='447MD4'),
        ),
        migrations.AlterField(
            model_name='jiapg2',
            name='j447md7',
            field=models.IntegerField(default=0, verbose_name='447MD7'),
        ),
    ]
