# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0008_auto_20171117_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_dat', models.DateField(verbose_name='日期')),
                ('jbss', models.IntegerField(default=0, verbose_name='加班时数')),
                ('jbxs', models.IntegerField(default=0, verbose_name='加班系数')),
                ('sbyl', models.IntegerField(default=0, verbose_name='水表用量')),
                ('sdj', models.IntegerField(default=0, verbose_name='单价')),
                ('wsf', models.IntegerField(default=0, verbose_name='污水费')),
                ('qbyl', models.IntegerField(default=0, verbose_name='汽表用量')),
                ('qdj', models.IntegerField(default=0, verbose_name='单价')),
                ('lbf', models.IntegerField(default=0, verbose_name='挂具维修费')),
                ('bzf', models.IntegerField(default=0, verbose_name='包装费')),
                ('bgf', models.IntegerField(default=0, verbose_name='修理费')),
                ('dzyh', models.IntegerField(default=0, verbose_name='低值易耗')),
                ('wlxh', models.IntegerField(default=0, verbose_name='物料消耗')),
                ('other', models.IntegerField(default=0, verbose_name='原料（药品）')),
            ],
            options={
                'ordering': ['-o_dat'],
                'verbose_name_plural': '其他费用表',
            },
        ),
    ]
