# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0012_maxmj'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxmj',
            name='pline',
            field=models.CharField(choices=[('1', 'PG2'), ('2', 'PG3'), ('3', 'PD3')], default='1', max_length=1, verbose_name='线别'),
        ),
    ]
