# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0013_maxmj_pline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quandata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total', models.IntegerField(default=0, verbose_name='总量')),
                ('baofeng', models.IntegerField(default=0, verbose_name='包风/出铁')),
                ('yaoshuiheng', models.IntegerField(default=0, verbose_name='药水痕')),
                ('shuiyin', models.IntegerField(default=0, verbose_name='水印/水渍')),
                ('fengbicanliu', models.IntegerField(default=0, verbose_name='封闭残留')),
                ('fahei', models.IntegerField(default=0, verbose_name='发黑')),
                ('fahuang', models.IntegerField(default=0, verbose_name='发黄')),
                ('fawu', models.IntegerField(default=0, verbose_name='发雾')),
                ('zangwu', models.IntegerField(default=0, verbose_name='脏污')),
                ('guashang', models.IntegerField(default=0, verbose_name='刮伤')),
                ('fancai', models.IntegerField(default=0, verbose_name='泛彩')),
                ('qipao', models.IntegerField(default=0, verbose_name='气泡')),
                ('seze', models.IntegerField(default=0, verbose_name='色泽/色差')),
                ('bianxing', models.IntegerField(default=0, verbose_name='变形')),
                ('cuose', models.IntegerField(default=0, verbose_name='错色')),
                ('dianzuoshang', models.IntegerField(default=0, verbose_name='电灼伤')),
                ('xiushi', models.IntegerField(default=0, verbose_name='锈蚀')),
            ],
            options={
                'verbose_name_plural': '全检数据',
            },
        ),
        migrations.CreateModel(
            name='Quanjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='客户')),
                ('jianming', models.CharField(max_length=50, verbose_name='件名')),
                ('jianhao', models.CharField(max_length=50, verbose_name='件号')),
            ],
            options={
                'verbose_name_plural': '全检名称设定',
            },
        ),
        migrations.AlterModelOptions(
            name='maxmj',
            options={'verbose_name_plural': '累积面积最大值设定'},
        ),
        migrations.AlterField(
            model_name='maxmj',
            name='maxV',
            field=models.IntegerField(default=0, verbose_name='最大值(万)'),
        ),
        migrations.AlterField(
            model_name='maxmj',
            name='yao',
            field=models.CharField(choices=[('1', '441A'), ('2', '444CS'), ('3', '447MD'), ('4', '124'), ('5', '444S'), ('5', '447S')], max_length=1, verbose_name='药水'),
        ),
        migrations.AlterField(
            model_name='yao',
            name='yao',
            field=models.CharField(choices=[('1', '441A'), ('2', '444CS'), ('3', '447MD'), ('4', '124'), ('5', '444S'), ('5', '447S')], max_length=1, verbose_name='药水'),
        ),
        migrations.AddField(
            model_name='quandata',
            name='quanjian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pline.Quanjian'),
        ),
    ]
