# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pline', '0015_auto_20171128_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='JianTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='JianYu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='槽名')),
                ('mianji', models.IntegerField(verbose_name='建浴面积（万）')),
            ],
            options={
                'verbose_name_plural': '建浴面积',
            },
        ),
        migrations.AlterField(
            model_name='costmonth',
            name='o_date',
            field=models.CharField(default='201712', help_text='请输入年份和月份', max_length=6, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='maxmj',
            name='yao',
            field=models.CharField(choices=[('1', '441A'), ('2', '444CS'), ('3', '447MD'), ('4', '124'), ('5', '444S'), ('6', '447S')], max_length=1, verbose_name='药水'),
        ),
        migrations.AlterField(
            model_name='yao',
            name='yao',
            field=models.CharField(choices=[('1', '441A'), ('2', '444CS'), ('3', '447MD'), ('4', '124'), ('5', '444S'), ('6', '447S')], max_length=1, verbose_name='药水'),
        ),
        migrations.AddField(
            model_name='jiantime',
            name='jianyu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pline.JianYu'),
        ),
    ]
